name: SCSS Lint, Compile, and Package

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: cd private && npm install

    - name: Compile SCSS to CSS
      run: cd private && npm run build:css

    - name: Run Tests
      run: cd private && npm test

    - name: Archive production artifacts
      run: zip -r AM-theme.zip . -x "*.git*" "node_modules/*" "private/node_modules/*" "*.DS_Store*"
      # Adjust the paths and exclusions according to your project structure

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: AM-theme-zip
        path: AM-theme.zip
